### PR TITLE
Make images mandatory

### PR DESCRIPTION
**Pull request by FinalAngel**
also prepare for release

### CODE REVIEW

**Comment by czpython** [comment]
@FinalAngel looks good, you'll need to generate the django migrations.

**Comment by czpython** [comment]
@FinalAngel please set ``max_length=254``.
On django 1.8 the default was changed to 254 but on 1.7 is still 75, because this migration was generated on 1.8 django detects the change and adds the necessary stuff for the new length but on 1.7 it would be inconsistent.
So best to specify it explicitly.

**Comment by FinalAngel** [comment]
added the change @czpython

**Comment by czpython** [comment]
:shipit:

**Pull request merged**
