### PR TITLE
Django 1.11 compatibility addressed

### PR DESCRIPTION
**Pull request by russmo**
Addressing #157 and #160. This time there is a workaround for backwards compatibility with Django <1.11.  RadioFieldRenderers are loaded up with a template if Django < 1.11.  If Django >= 1.11, then template based rendering is used.  Django 1.11 reworked the whole widget rendering codebase in favor or templates.

### CODE REVIEW

**Comment by russmo** [comment]
Any reason not to move this forward?

**Comment by zachrank** [comment]
It'd be awesome if we could get this resolved before the New Year!

**Comment by russmo** [comment]
I have addressed the changes requested by @czpython .  I have also pushed through a bunch of changes to make this compatible with Django 2.0.  The rest of django-cms needs to move towards Django 2.0 support, but this plugin will work once it gets there.

**Comment by stefanfoulis** [comment]
On Django 1.11 the file picker on the image plugin looks lilke this: 
screen shot 2018-03-13 at 23 50 26
Other than that it seems to work fine.

**Comment by vxsx** [comment]
@stefanfoulis could you check with latest master of djangocms-admin-style? https://github.com/divio/djangocms-admin-style/commit/57b3c239d148454a8189d9fbeb68d3588ea235b6 should fix it

**Comment by stefanfoulis** [comment]
@vxsx With djangocms-admin-style master:
screen shot 2018-03-14 at 13 18 37

Without djangocms-admin-style:
screen shot 2018-03-14 at 13 19 15

**Comment by vxsx** [comment]
will fix, thanks @stefanfoulis

**Comment by AndrewMoonLight** [comment]
Hi! I am new in programming and in Django also. Could You explain how can I install these changes?
I have such problem - 

I'm trying out aldryn-bootstrap3 with Django 1.11.3 and I get the following error:

File "/opt/myvirtualenv/project_virtual_env/lib/python3.5/site-packages/aldryn_bootstrap3/widgets.py", line 10, in 
class ContextRenderer(django.forms.widgets.RadioFieldRenderer):
AttributeError: module 'django.forms.widgets' has no attribute 'RadioFieldRenderer'.

I have no idea how to fix this?

**Comment by AndrewMoonLight** [comment]
Hi! I am new in programming and in Django also. Could You explain how can I install these changes?
I have such problem - 

I'm trying out aldryn-bootstrap3 with Django 1.11.3 and I get the following error:

> File "/opt/myvirtualenv/project_virtual_env/lib/python3.5/site-packages/aldryn_bootstrap3/widgets.py", line 10, in 
> class ContextRenderer(django.forms.widgets.RadioFieldRenderer):
> AttributeError: module 'django.forms.widgets' has no attribute 'RadioFieldRenderer'.

I have no idea how to fix this?

**Pull request merged**
