### PR TITLE
Fix after django-filer has been released

### PR DESCRIPTION
**Pull request by FinalAngel**
remove the dependency to filer migration - this has been added to filer

### CODE REVIEW

**Comment by intellectronica** [comment]
:+1:

**Comment by stefanfoulis** [comment]
:+1:

**Comment by stefanfoulis** [comment]
ah wait... you should set the correct filer dependency in setup.py

**Comment by stefanfoulis** [comment]
``REQUIREMENTS`` in ``setup.py`` should be ``'django-filer>=0.9.11',`` for django-filer.

**Comment by FinalAngel** [comment]
done

**Pull request merged**
